services:
  elasticsearch:
    image: elasticsearch:9.2.1
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -u elastic:$$ELASTIC_PASSWORD -s http://localhost:9200/_cluster/health | grep -E 'yellow|green'"
        ]
      interval: 15s
      retries: 10
      timeout: 10s
      start_period: 60s # Give more time for initial bootstrap
    env_file:
      - ../../.env
    environment:
      - discovery.type=single-node
      #- xpack.security.enabled=false
      - xpack.security.enabled=true # Enable for prod; set ELASTIC_PASSWORD below
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD} 
      - ES_JAVA_OPTS=-Xms2g -Xmx2g  # Scale based on load/host RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536  # High file descriptors for indexing
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - data-ops-network
  kibana:
    image: kibana:9.2.1  
    container_name: kibana
    restart: unless-stopped
    ports:
      - "5601:5601"  # Standard Kibana port
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Points to ES container name
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=${ELASTICSEARCH_SERVICEACCOUNTTOKEN}
      - XPACK_SECURITY_ENABLED=true  # Matches your ES security
    depends_on:
      elasticsearch:
        condition: service_healthy  # Waits for ES healthcheck
    healthcheck:
      #test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status"]
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 15s
      retries: 5
      timeout: 5s
      start_period: 40s
    networks:
      - data-ops-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

################################ Networks ############################################
networks:
  data-ops-network:
    external: true 

################################ Volumes ############################################
volumes:
  elasticsearch_data:
    name: elasticsearch_data
