# config/schemas/mysql/database1/accounts.yaml
table_name: products

source:
  database: amtdb
  table: products

target:
  database: test
  table: test_products
  sync_metadata:
    enabled: true
    columns:
      sync_at:
        enabled: true
        type: DateTime
        description: "Timestamp when record was synced"
columns:
  - name: id
    target_name: id
    source_type: int
    target_type: Int64
    primary_key: true
    nullable: false
  
  - name: companyRegionId
    target_name: company_region_id
    source_type: int
    target_type: Int64
    nullable: true

  - name: productTypeId
    target_name: product_type_id
    source_type: int
    target_type: Int64
    nullable: true
  
  - name: product
    target_name: product
    source_type: varchar(100)
    target_type: String
    nullable: true

  - name: createdAt
    target_name: created_at
    source_type: datetime
    target_type: DateTime
    nullable: false

  - name: updatedAt
    target_name: updated_at
    source_type: timestamp
    target_type: DateTime
    nullable: false